version: "2"
services:
  mongodb:
    image: mongo
    container_name: mongodb
  #  volumes:
      #- ./data/:/data/db
  games_app:
    build: .
    container_name: gamesApp
    ports:
      - "3000:3000"
    depends_on:
        - "mongodb"
    links:
        - mongodb
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
        - "games_app"
    links:
        - games_app
    ports:
      - "80:8080"
